#### Aquí encontrarás todo lo que necesitas saber: https://www.kaggle.com/t/ab8726f0cfc84544abbae69a6be88071

## Librerias

In [13]:
import pandas as pd

import urllib.request
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Data

In [14]:
### Para que funcione necesitas bajarte los archivos de datos de Kaggle 
train = pd.read_csv('C:/Users/jegar/OneDrive/Documentos/CLIENTES/BRIDGE/Machine_Learning/1-Supervisado/2-Classification/Kaggle2/data/train.csv')
test = pd.read_csv('C:/Users/jegar/OneDrive/Documentos/CLIENTES/BRIDGE/Machine_Learning/1-Supervisado/2-Classification/Kaggle2/data/test.csv')



## Data exploration

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73363 entries, 0 to 73362
Data columns (total 12 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Id                                    73363 non-null  int64  
 1   target                                73363 non-null  int64  
 2   RevolvingUtilizationOfUnsecuredLines  73363 non-null  float64
 3   age                                   73363 non-null  object 
 4   NumberOfTime30-59DaysPastDueNotWorse  73363 non-null  int64  
 5   DebtRatio                             73363 non-null  float64
 6   MonthlyIncome                         58796 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       73363 non-null  int64  
 8   NumberOfTimes90DaysLate               73363 non-null  int64  
 9   NumberRealEstateLoansOrLines          73363 non-null  int64  
 10  NumberOfTime60-89DaysPastDueNotWorse  73363 non-null  int64  
 11  NumberOfDepende

In [16]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31442 entries, 0 to 31441
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Id                                    31442 non-null  int64  
 1   RevolvingUtilizationOfUnsecuredLines  31442 non-null  float64
 2   age                                   31442 non-null  object 
 3   NumberOfTime30-59DaysPastDueNotWorse  31442 non-null  int64  
 4   DebtRatio                             31442 non-null  float64
 5   MonthlyIncome                         25228 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       31442 non-null  int64  
 7   NumberOfTimes90DaysLate               31442 non-null  int64  
 8   NumberRealEstateLoansOrLines          31442 non-null  int64  
 9   NumberOfTime60-89DaysPastDueNotWorse  31442 non-null  int64  
 10  NumberOfDependents                    30635 non-null  float64
dtypes: float64(4), 

In [17]:
test['age'] = test['age'].str.replace('y', '')
test['age'] = test['age'].astype('Int64')

In [18]:
train['age'] = train['age'].str.replace('y', '')
train['age'] = train['age'].astype('Int64')


In [19]:
train['NumberOfDependents'].unique()

array([ 0.,  1.,  2.,  4.,  3., nan,  7.,  5.,  6.,  9.,  8., 13.])

In [20]:
train['MonthlyIncome'].unique()

array([ 2178.,  3750.,  6833., ...,  8109., 20776.,  8940.])

In [21]:
media = train['NumberOfDependents'].mean()
train['NumberOfDependents'].fillna(media, inplace=True)
media = train['MonthlyIncome'].mean()
train['MonthlyIncome'].fillna(media, inplace=True)
media_ = test['NumberOfDependents'].mean()
test['NumberOfDependents'].fillna(media_, inplace=True)
media_ = test['MonthlyIncome'].mean()
test['MonthlyIncome'].fillna(media_, inplace=True)

In [22]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73363 entries, 0 to 73362
Data columns (total 12 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Id                                    73363 non-null  int64  
 1   target                                73363 non-null  int64  
 2   RevolvingUtilizationOfUnsecuredLines  73363 non-null  float64
 3   age                                   73363 non-null  Int64  
 4   NumberOfTime30-59DaysPastDueNotWorse  73363 non-null  int64  
 5   DebtRatio                             73363 non-null  float64
 6   MonthlyIncome                         73363 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       73363 non-null  int64  
 8   NumberOfTimes90DaysLate               73363 non-null  int64  
 9   NumberRealEstateLoansOrLines          73363 non-null  int64  
 10  NumberOfTime60-89DaysPastDueNotWorse  73363 non-null  int64  
 11  NumberOfDepende

In [23]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31442 entries, 0 to 31441
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Id                                    31442 non-null  int64  
 1   RevolvingUtilizationOfUnsecuredLines  31442 non-null  float64
 2   age                                   31442 non-null  Int64  
 3   NumberOfTime30-59DaysPastDueNotWorse  31442 non-null  int64  
 4   DebtRatio                             31442 non-null  float64
 5   MonthlyIncome                         31442 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       31442 non-null  int64  
 7   NumberOfTimes90DaysLate               31442 non-null  int64  
 8   NumberRealEstateLoansOrLines          31442 non-null  int64  
 9   NumberOfTime60-89DaysPastDueNotWorse  31442 non-null  int64  
 10  NumberOfDependents                    31442 non-null  float64
dtypes: Int64(1), fl

-----------------------------------------------------------------------------------------------------------------

## Pasos que si o si debéis realizar para poder participar en la competición:

### 1. Definir X e y

In [24]:
X = train.drop(['target'], axis=1)
y = train['target'].copy()
X.shape


(73363, 11)

In [25]:
y.shape

(73363,)

### 2. Dividir X_train, X_test, y_train, y_test

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

### 3. Asignar el modelo (vacío) a una variable


In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [29]:
model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [30]:
pred = model.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### 4. Sacar métricas, valorar el modelo 

Recuerda que en la competición se va a evaluar con la métrica de AUC.

In [31]:
from sklearn.metrics import roc_auc_score
import numpy as np
print('AUC :',roc_auc_score(y_test, pred))


AUC : 0.5038505642220943


-----------------------------------------------------------------

## Una vez listo el modelo, toca predecir con el dataset de predicción 

Definición de **modelo que está listo**. 

Tras hacer suficientes pruebas, analizar los datos, hacer feature engineering, probar diferentes modelos con diferentes parámetros, es con este con el que observo mejores métricas y menos overfitting. ¡Cuidado con el overfitting aquí! Si vuestro modelo aprende muy bien de estos datos pero hay overfitting cuando le pasemos los datos desconocidos de `test.csv` nos arriesgamos a que digamos, no salga lo esperado.

### 1. Entrena dicho modelo con TODOS tus datos de train, esto es con `train.csv` al completo.


**CON LAS TRANSFORMACIONES QUE LE HAYAS REALIZADO A `X` INCLUÍDAS.**


Véase:
- Estandarización/Normalización
- Eliminación de Outliers
- Eliminación de columnas
- Creación de columnas nuevas
- Gestión de valores nulos
- Y un largo etcétera de técnicas que como Data Scientist hayas considerado las mejores para tu dataset.

### 2. Carga los datos de `test.csv` para predecir.

In [32]:
test.head()

Id  RevolvingUtilizationOfUnsecuredLines  age   
0  15576                              0.051782   53  \
1  94308                              0.022133   57   
2  53983                              0.013693   68   
3  61359                              0.018568   74   
4  71383                              0.008630   66   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome   
0                                     0   0.009350    2245.000000  \
1                                     0   0.319562    7672.000000   
2                                     0   0.139237    4064.000000   
3                                     0   0.018760   10500.000000   
4                                     0   9.000000    6766.741597   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate   
0                                3                        0  \
1                               26                        0   
2                                4                        0   
3                               27                        0   
4                                5                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse   
0                             0                                     0  \
1                             1                                     0   
2                             0                                     0   
3                             0                                     0   
4                             0                                     0   

   NumberOfDependents  
0                 0.0  
1                 2.0  
2                 1.0  
3                 0.0  
4                 0.0

In [33]:
test

Id  RevolvingUtilizationOfUnsecuredLines  age   
0       15576                              0.051782   53  \
1       94308                              0.022133   57   
2       53983                              0.013693   68   
3       61359                              0.018568   74   
4       71383                              0.008630   66   
...       ...                                   ...  ...   
31437  110527                              0.469451   28   
31438  121978                              0.171910   44   
31439   77327                              0.004842   51   
31440   48341                              0.636554   42   
31441   37695                              0.011406   53   

       NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome   
0                                         0     0.009350    2245.000000  \
1                                         0     0.319562    7672.000000   
2                                         0     0.139237    4064.000000   
3                                         0     0.018760   10500.000000   
4                                         0     9.000000    6766.741597   
...                                     ...          ...            ...   
31437                                     0     0.029072    2166.000000   
31438                                     0     0.375557    5833.000000   
31439                                     1    30.000000       0.000000   
31440                                     0     0.483931    7000.000000   
31441                                     0  2813.000000    6766.741597   

       NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate   
0                                    3                        0  \
1                                   26                        0   
2                                    4                        0   
3                                   27                        0   
4                                    5                        0   
...                                ...                      ...   
31437                                1                        0   
31438                                8                        0   
31439                                3                        0   
31440                               10                        2   
31441                               17                        0   

       NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse   
0                                 0                                     0  \
1                                 1                                     0   
2                                 0                                     0   
3                                 0                                     0   
4                                 0                                     0   
...                             ...                                   ...   
31437                             0                                     0   
31438                             2                                     0   
31439                             0                                     0   
31440                             1                                     0   
31441                             1                                     0   

       NumberOfDependents  
0                     0.0  
1                     2.0  
2                     1.0  
3                     0.0  
4                     0.0  
...                   ...  
31437                 0.0  
31438                 4.0  
31439                 2.0  
31440                 1.0  
31441                 0.0  

[31442 rows x 11 columns]

**¿Por qué da error?** 

In [34]:
predictions_submit = model.predict(test)
predictions_submit

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

IMPORTANTE: APLICAR LO MISMO A ESTOS DATOS QUE HAYÁIS APLICADO A LOS DATOS DE ENTRENAMIENTO

- SI EL ARRAY CON EL QUE HICISTEIS `.fit()` ERA DE 4 COLUMNAS, PARA `.predict()` DEBEN SER LAS MISMAS
- SI AL ARRAY CON EL QUE HICISTEIS `.fit()` LO NORMALIZASTEIS, PARA `.predict()` DEBÉIS NORMALIZARLO
- TODO IGUAL SALVO BORRAR FILAS, EL NÚMERO DE ROWS SE DEBE MANTENER EN ESTE SET, PUES LA PREDICCIÓN DEBE TENER 391 FILAS, SI O SI

**Entonces, si al cargar los datos de train usé `index_col=0` para que utilizara la primera columna del conjunto de datos como índice, ¿tendré que hacerlo también para el conjunto `test.csv`?**

In [35]:
# ¿Qué opináis?
# Sí

![](https://www.tierraljelechu.com/web/img/wiki_up/1.996-SorpresaDto.-1-Red.jpg)

### 3. AHORA puedo hacer la predicción que será lo que subirás a Kaggle. 

**¿Qué es lo que subirás a Kaggle?**

In [36]:
predictions_submit = model.predict(test)
predictions_submit

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

**¡PERO! Para subir a Kaggle la predicción, ésta tendrá que tener una forma específica y no valdrá otra.**

En este caso, la **MISMA** forma que `sample_submission.csv`. 

In [37]:
sample = pd.read_csv("data/sample_submission.csv")

In [38]:
sample.head()

Id  target
0  15576       0
1  94308       1
2  53983       1
3  61359       1
4  71383       0

In [39]:
sample.shape

(31442, 2)

### 4. Mete tus predicciones en un dataframe. 

En este caso, la **MISMA** forma que `sample_submission.csv`. 

In [40]:
submission = pd.DataFrame({"Id": sample['Id'], "target": predictions_submit})

In [41]:
submission.head()

Id  target
0  15576       0
1  94308       0
2  53983       0
3  61359       0
4  71383       0

In [42]:
submission.shape

(31442, 2)

### 5. Pásale el CHEQUEATOR para comprobar que efectivamente está listo para subir a Kaggle.

In [43]:
def chequeator(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.
    
    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.
    
    Si no, LEE EL MENSAJE Y HAZLE CASO.
    
    Si aún no:
    - apaga tu ordenador, 
    - date una vuelta, 
    - enciendelo otra vez, 
    - abre este notebook y 
    - leelo todo de nuevo. 
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.Id.all() == sample.Id.all():
                print("You're ready to submit!")
                submission.to_csv("submission.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://i.kym-cdn.com/photos/images/facebook/000/747/556/27a.jpg", "gfg.png")     
                img = Image.open("gfg.png")
                img.show()   
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto de Clara: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `diamonds_test.csv`. Lloro.")


In [44]:
chequeator(submission)

You're ready to submit!
